apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gkms
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-gkms@sha256:5eee63092b9b5b376e6997c0a8d667e86f3305d4e0011aa481a02c851759989f
        name: my-nodejs
        resources: {}
status: {}
